# Habilita a interface Swagger-UI
quarkus.smallrye-openapi.ui.enable=true
# Define o caminho para acessar o swagger
quarkus.smallrye-openapi.path=/swagger-ui

# Metadados da sua API
mp.openapi.extensions.smallrye.info.title=Consulting AI Mining API
mp.openapi.extensions.smallrye.info.version=1.0.0
mp.openapi.extensions.smallrye.info.description=API para mineração e análise de compatibilidade de currículos com vagas.

# Configuração de Conexão com o MySQL do Aiven
quarkus.datasource.db-kind=mysql
quarkus.datasource.username=${DB_USER}
quarkus.datasource.password=${DB_PASSWORD}
quarkus.datasource.jdbc.url=${DB_HOST}

# Configuração do Hibernate ORM com Panache
quarkus.hibernate-orm.database.generation=update
# Se quiser que o Hibernate mapeie a entidade para a tabela com o prefixo exato:
# (ou faremos isso via anotação @Table na entidade Java)

#GROQ API KEY
groq.api.key=${GROQ_API_KEY}
groq.api.url=${GROQ_API_URL}